### ISSUE TITLE
ERROR: Could not establish SIFT connection, aborting! 

### ISSUE THREAD

**Issue by jkoptimize** [snipersim/snipersim#2]
hi, may i ask a question, when I'm running splash2 benchmarks with own script, and use the following command:
`./run-sniper --benchmarks=splash2-fft-small-8,splash2-radix-small-8,splash2-lu.ncont-small-8 -c base_orig.cfg -c ./a72_orig.cfg,./a72_orig.cfg,./a72_orig.cfg,./a72_orig.cfg,./a53_orig.cfg,./a53_orig.cfg,./a53_orig.cfg,./a53_orig.cfg -n 8 -d ./result -s ./proposed_algorithm.py`
here comes the problem:

[app2] [SPLASH] [---------- Beginning of output ----------] 
[SNIPER] Start
Core 0 at 2.36 GHz (global clock 1.00 GHz)
Core 1 at 2.36 GHz (global clock 1.00 GHz)
Core 2 at 2.36 GHz (global clock 1.00 GHz)
Core 3 at 2.36 GHz (global clock 1.00 GHz)
Core 4 at 1.84 GHz (global clock 1.00 GHz)
Core 5 at 1.84 GHz (global clock 1.00 GHz)
Core 6 at 1.84 GHz (global clock 1.00 GHz)
Core 7 at 1.84 GHz (global clock 1.00 GHz)
name: network.shmem-1.bus
Core: 0
Core: 1
Core: 2
Core: 3
Core: 4
Core: 5
Core: 6
Core: 7
Executing Python script /home/ubuntu/benchmarks/result/sim.scripts.py
pandas path: /home/ubuntu/benchmarks/sniper-7.4/python_kit/intel64/lib/python2.7/site-packages/pandas/__init__.pyc
0 -1 0
[Schedule] Schedule thread-0 to core 0 time:  0
[Schedule] Thread -1 create thread-0 at 0 vruntime 4e+12 core 0
1 -1 0
[Schedule] Schedule thread-1 to core 1 time:  0
[Schedule] Thread -1 create thread-1 at 0 vruntime 2e+12 core 1
2 -1 0
[Schedule] Schedule thread-2 to core 2 time:  0
[Schedule] Thread -1 create thread-2 at 0 vruntime 2e+12 core 2
[SNIPER] --------------------------------------------------------------------------------
[SNIPER] Sniper using SIFT/trace-driven frontend
[SNIPER] Running full application in DETAILED mode
[SNIPER] --------------------------------------------------------------------------------
[SNIPER] Enabling performance models
[SNIPER] Setting instrumentation mode to DETAILED
[SNIPER] WARNING: No SIFT connections made yet. Waiting...
[SNIPER] ERROR: Could not establish SIFT connection, aborting! Check benchmark-app*.log for errors.
[SNIPER] End
[SNIPER] Elapsed time: 60.77 seconds
clean tmp file

I'm really confused with this problem, Is there probably something wrong while building Sniper?
OS version is Ubuntu18.04, and I follow the guide on official website.

**Comment by trevorcarlson** [comment]
@jkoptimize, thanks for posting this. At first glance, this appears that this is an issue with the `run_sniper.run_multi()` routine in `$SNIPER_ROOT/tools/run_sniper.py`. Your Sniper compiles appear to be working properly. In addition, I was able to reproduce this using the latest snipersim/snipersim DockerHub image.

**Comment by trevorcarlson** [comment]
@jkoptimize, I've fixed this in b58797c3. I've also pushed an [updated version of the benchmarks](https://hub.docker.com/repository/docker/snipersim/snipersim). Please try things out and let us know if you run into any other issues.
